services:
  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    networks:
      - app-network
    environment:
      - PYTHONUNBUFFERED=1
      - DB_HOST=localhost
      - DB_USER=root
      - DB_PASSWORD=test123
      - DB_DATABASE=laravel
      - DB_PORT=3306

networks:
  app-network:
    driver: bridge
